version: '3.8'
services:
  backend:
    build:
      context: ./application/backend
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - redis
      - rabbitmq

  # frontend:
  #   build:
  #     context: ./application/frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

  consumer:
    build:
      context: ./application/consumer
    environment:
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"